framework:
    assets:
        packages:
            login:
                json_manifest_path: '%kernel.project_dir%/public/build/login/manifest.json'
            dashboard:
                json_manifest_path: '%kernel.project_dir%/public/build/dashboard/manifest.json'
